/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Fallback: typeof import('./../src/components/common/Fallback.vue')['default']
    Form: typeof import('./../src/components/common/form/form.vue')['default']
    FormItem: typeof import('./../src/components/common/form/form-render/form-item.vue')['default']
    FormLabel: typeof import('./../src/components/common/form/form-render/form-label.vue')['default']
    FormRender: typeof import('./../src/components/common/form/form-render/form-render.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    Icon403: typeof import('./../src/components/common/icons/icon-403.vue')['default']
    Icon404: typeof import('./../src/components/common/icons/icon-404.vue')['default']
    Icon500: typeof import('./../src/components/common/icons/icon-500.vue')['default']
    IconComingSoon: typeof import('./../src/components/common/icons/icon-coming-soon.vue')['default']
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconOffline: typeof import('./../src/components/common/icons/icon-offline.vue')['default']
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NWatermark: typeof import('naive-ui')['NWatermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCaptcha: typeof import('./../src/components/common/captcha/slider-captcha/index.vue')['default']
    SliderCaptchaAction: typeof import('./../src/components/common/captcha/slider-captcha/slider-captcha-action.vue')['default']
    SliderCaptchaBar: typeof import('./../src/components/common/captcha/slider-captcha/slider-captcha-bar.vue')['default']
    SliderCaptchaContent: typeof import('./../src/components/common/captcha/slider-captcha/slider-captcha-content.vue')['default']
    SpineText: typeof import('./../src/components/common/captcha/slider-captcha/spine-text.vue')['default']
    TheWelcome: typeof import('./../src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../src/components/WelcomeItem.vue')['default']
  }
}
